# CoPingLauncher.ps1
[CmdletBinding()]
param([string]$FromFile,[string]$FromUrl,[switch]$HitEnter)
$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $here 'CoPing.psm1') -Force
if ($FromFile) { Invoke-CoPing -FromFile $FromFile -HitEnter:$HitEnter; exit }
if ($FromUrl)  { Invoke-CoPing -FromUrl  $FromUrl  -HitEnter:$HitEnter; exit }
throw "Specify -FromFile or -FromUrl"
# SIG # Begin signature block
# MIIFjAYJKoZIhvcNAQcCoIIFfTCCBXkCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBdMRI2zxU7MX9G
# ZRTw2EkQNzCzbuXpAUkG5iD+QzmkGKCCAwQwggMAMIIB6KADAgECAhBA9a8p9kJq
# gEvoqXEAmoJ5MA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMMDUNvTW9kdWxlcyBE
# ZXYwHhcNMjUwOTA1MTc1MDM5WhcNMjYwOTA1MTgxMDM5WjAYMRYwFAYDVQQDDA1D
# b01vZHVsZXMgRGV2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2dw6
# iFLyaavQTn4hDT6SqThIesb3LnKHyCVOvUsJ0vL549+2JvMDvL9KENRvKswYB6kp
# OzPPn5PVOirYxXte/tGs6eKyWS0tUg2SVsEw1bSwZYv/47UjzyV5flEnPb5E0wkS
# q16dqL1a6xhCylkCWbbuc1k5xlP4cbdTJL/x/Z/Uc1MBd50LxcvzbbYXWsoQlxh9
# QhTMviBkOPUSJ7OH5EmoS1zWj9yMpMtQPWsHxOfDbx3LXIH+sJ9dFbY+Gzg+XmCt
# Biijkt1nO0ZHl41tcLOS1iwfpBP9efj7fAmCma9yLIuRk56nLIOXy14DKuCXMo6J
# M5GX8WRmwCyeP3GXMQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFGDbSGZBfORpT4uijbMW5ShZ5UWyMA0GCSqG
# SIb3DQEBCwUAA4IBAQAnrvPwqigCpaNqluJEyfI4CgF+leKcPs9xzixdsMcS4llj
# i7w9Qxp/h2b/64RwRv7rO8NEXaryHyzSzfPpvsQj1I45P5gwumXZI8QCs8jz41MH
# aQ+4jwiw8DmZ0H66V8Vb//VbD/snw1b9Kfi5vA8j1nEe81NO8QEqnEW6JEP5Ca7t
# qjXwnVvA5WFdxFponab9/wh/JklFjcuz3sG6+YMhMyFlIluZkgpszEfzedstMao0
# pjssH3rqRPGCB6GbPiyfiBJ5kgqdiW9qRggcQxA2hfOX3VoCZ9M/I3DtCm69tn7F
# P2zM6krnx9LLjHpfjmfY8ZHOXDbO7fZ0lp3xJ8KOMYIB3jCCAdoCAQEwLDAYMRYw
# FAYDVQQDDA1Db01vZHVsZXMgRGV2AhBA9a8p9kJqgEvoqXEAmoJ5MA0GCWCGSAFl
# AwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkD
# MQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJ
# KoZIhvcNAQkEMSIEIDQI6dsFtAiAInBK7NWp1bRxNOnSFGssxqNzq2C6OtJ3MA0G
# CSqGSIb3DQEBAQUABIIBAGsOE09F8hkAvtkEDxf4P5uQMfGE0NjWaAv9Mh+4PxLb
# r9/0i3kB2NbpclVUMThhd/WewoiQWMekhmVIFq0zlsMZTQohXtWnNJWNSvCEPP1S
# VROUau5DAXMKxujqEF7fcSt0N1M+1pKQO1uEUPkGutRbudwe3w0SPIAVAV5NN5z4
# yilJow1uI546OUXQLXbpVIFxNMSGgow6GdjPXOq3K6PCJJW0+Cze56M4K+nYrkiU
# FLbqye+EildgUPhbP529WnLKD2k6AszHn87B7wWpv4YV4ar8nPKkl0xH/Hsp/U+6
# oXr643WkWW/H8yugf4j1M0rb0wr24e8SZQMaEuK+lNw=
# SIG # End signature block
