name: CI (skeleton)
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show tree
        run: |
          git --version
          ls -laR

