name: index-check
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  index:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs index
        shell: pwsh
        run: ./tools/build-index.ps1
      - name: Verify docs/index is up to date
        shell: pwsh
        run: |
          git status --porcelain docs/index | % { $_ } | ForEach-Object {
            Write-Host "::error::docs/index is out of date. Run tools/build-index.ps1 and commit."
            git --no-pager diff -- docs/index | Out-String | Write-Host
            exit 1
          }
