name: index-check
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell 7
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
      - name: Build docs index
        run: pwsh -NoLogo -NoProfile -File ./tools/build-index.ps1
      - name: Verify docs/index is up to date
        run: |
          if git status --porcelain docs/index | grep .; then
            echo "::error::docs/index is out of date. Run tools/build-index.ps1 and commit."
            git --no-pager diff -- docs/index | tail -n +1 || true
            exit 1
          fi
