# ps-tests.yml
name: PS Tests
on: [push, pull_request]
jobs:
  pester:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        run: pwsh -NoProfile -Command "Install-Module Pester -Scope CurrentUser -Force"
      - name: Run BPOE heartbeat tests
        run: pwsh -NoProfile -Command "Invoke-Pester -CI -Path tests"